sudo: required

os:
  - linux
  - osx

language: cpp

compiler:
  - clang
  - gcc

before_install:
## Install CMake 2.8.8
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:kalakris/cmake -y; sudo apt-get update -qq; sudo apt-get install cmake valgrind; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install cmake valgrind; fi

before_script:
  - mkdir build
  - cd build
  - cmake .. -DGISMO_WITH_ONURBS=ON #-DGISMO_WITH_IPOPT=ON
  - ctest -D ExperimentalConfigure

script:
  - ctest -j2 -D ExperimentalBuild
  - ctest -j2 -D ExperimentalTest
  - ctest -j2 -D ExperimentalMemCheck
  - ctest -j2 -D ExperimentalSubmit
#- make -j3 Experimental
#- make -j3 ExperimentalMemCheck
