sudo: required

language: cpp

compiler:
  - clang
  - gcc

before_install:
## Install CMake 2.8.8
- sudo add-apt-repository ppa:kalakris/cmake -y
- sudo apt-get update -qq
- sudo apt-get install cmake
- sudo apt-get install valgrind

before_script:
  - mkdir build
  - cd build
  - cmake .. -DGISMO_WITH_ONURBS=ON #-DGISMO_WITH_IPOPT=ON
  - ctest -D ExperimentalConfigure

script:
  - ctest -j2 -D ExperimentalBuild
  - ctest -j2 -D ExperimentalTest
  - ctest -j2 -D ExperimentalMemCheck
  - ctest -j2 -D ExperimentalSubmit
#- make -j3 Experimental
#- make -j3 ExperimentalMemCheck
