sudo: required
#sudo: false

os:
  - linux
  - osx

language: cpp

compiler:
  - clang
  - gcc

before_install:
# Install CMake 2.8.8
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:kalakris/cmake -y; sudo apt-get update -qq; sudo apt-get install cmake valgrind; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install valgrind; fi #brew update;

#addons:
#  apt:
#    packages:
#    - cmake
#    - valgrind
#    #- time

before_script:
  - mkdir build; cd build
  - cmake .. -DGISMO_WITH_ONURBS=ON -DSITE="travis-ci.org" #-DGISMO_WITH_IPOPT=ON

script:
  - ctest -j2 -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalMemCheck -D ExperimentalSubmit -V
  #- make -j2 Experimental
  #- make -j2 ExperimentalMemCheck
