# Specify version format
version: "G+Smo-stable.{build}"

# Operating system (build VM template)
#os: 
#  - Windows Server 2012 R2
#  - Default Azure
#  - SharePoint 2013
#  - MinGW
#  - Visual Studio 2014 CTP4
#  - Visual Studio 2015 RC

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
  - BUILD: msvc
    platform: Win32
  - BUILD: msvc
    platform: x64
  - BUILD: mingw

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
#platform: 
#  - Win32
#  - x64

#artifacts:
#  - path: tt
#    name: ipopt
#    type: dll

# specify custom environment variables
# environment:
#  BOOST_ROOT: c:\Libraries\boost
#  BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib

# set clone depth
#clone_depth: 5 # clone entire repository history if not defined
shallow_clone: true

# build Configuration, i.e. Debug, Release, etc.
configuration:
#  - Debug
#  - RelWithDebInfo
  - Release

# scripts that are called at very beginning, before repo cloning
init:
#  - cmd: cmake --version
# - cmd: echo Platform is %platform%
 - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\gismo

# branches to build
branches:
  # stable
  except:
    - gh-pages

# Do not build on tags (GitHub only)
skip_tags: true

# scripts that run after cloning repository
install:
  - cmd: cd C:\projects
  - cmd: md build-gismo

# scripts to run before build
before_build:
  - cmd: cd build-gismo
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: if "%BUILD%"=="msvc" ( if "%platform%"=="x64" (set CMAKE_GENERATOR_NAME="Visual Studio 14 2015 Win64") else (set CMAKE_GENERATOR_NAME="Visual Studio 14 2015" ) )
  - cmd: if "%BUILD%"=="mingw" set CMAKE_GENERATOR_NAME="MinGW Makefiles"
  - cmd: echo Configuring %CMAKE_GENERATOR_NAME% %configuration%
#  - cmd: set
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DGISMO_WITH_ONURBS=ON ../gismo

build_script:
  - ps: |
      if (%BUILD%=="mingw") (
        mingw32-make -j4
      ) else (
        msbuild /m:4 /p:Configuration=%configuration% /verbosity:minimal C:\projects\build-gismo\gismo.sln
      )

#build:
#  project: C:\projects\build-gismo\gismo.sln
  # enable MSBuild parallel builds
#  parallel: true

  # MSBuild verbosity level (quiet|minimal|normal|detailed)
#  verbosity: minimal

  # NuGet
  #publish_nuget: true
  #publish_nuget_symbols: true
  #include_nuget_references: true

test_script:
  - cmd: ctest -C %configuration% -VV -D Experimental
