version: 2.0

jobs:
  macos_x86_64_xcode14.3_cxx14_release:
    macos:
      xcode: "14.3.1"
    resource_class: macos.x86.medium.gen2
    working_directory: ~/gismo
    environment:
      MAKEJOBS: 4
    steps:
      - run:
          name: Install dependencies
          command: brew install cmake
      - checkout
      - run:
          name: Configure G+Smo on MacOS
          command: cmake . -DCMAKE_QUIET=ON -DBUILDNAME="macos_x86_64_xcode14.3_cxx14_release" -DSITE="$CIRCLE_USERNAME-$CIRCLE_BRANCH [cci]" -DGISMO_INSOURCE_BUILD=ON -DGISMO_BUILD_UNITTESTS=ON -DCMAKE_CXX_STANDARD=11 -DGISMO_OPTIONAL="gsOpennurbs"
      - run:
          name: Build and test G+Smo on MacOS (x86_64)
          command: ctest -S cmake/ctest_script.cmake -D KEEPCONFIG=ON -D CTEST_BUILD_JOBS=$MAKEJOBS

  macos_arm64_xcode14.3_cxx14_release:
    macos:
      xcode: "14.3.1"
    resource_class: macos.m1.medium.gen1
    working_directory: ~/gismo
    environment:
      MAKEJOBS: 4
    steps:
      - run:
          name: Install dependencies
          command: brew install cmake
      - checkout
      - run:
          name: Configure G+Smo on MacOS (arm64)
          command: cmake . -DCMAKE_QUIET=ON -DBUILDNAME="macos_x86_64_xcode14_cxx14_release" -DSITE="$CIRCLE_USERNAME-$CIRCLE_BRANCH [cci]" -DGISMO_INSOURCE_BUILD=ON -DGISMO_BUILD_UNITTESTS=ON -DCMAKE_CXX_STANDARD=14 -DGISMO_OPTIONAL="gsOpennurbs"
      - run:
          name: Build and test G+Smo on MacOS
          command: ctest -S cmake/ctest_script.cmake -D KEEPCONFIG=ON -D CTEST_BUILD_JOBS=$MAKEJOBS

workflows:
  version: 2
  build:
    jobs:
      - macos_x86_64_xcode14.3_cxx14_release
      - macos_arm64_xcode14.3_cxx14_release
